spring:
  config:
    activate:
      on-profile: dev
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: none # def:none 본인 테스트 환경에 따라 조정할 것
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST_NAME}/${DB_STORAGE_NAME}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DB_AUTH_ID}
    password: ${DB_AUTH_PASSWORD}